/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCardsRouteImport } from './routes/_authenticated/cards'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStatementsRouteImport } from './routes/_authenticated/statements'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGateRouteRouteImport } from './routes/admin/_gate/route'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGateActivityLogsRouteImport } from './routes/admin/_gate/activity-logs'
import { Route as AdminGateAnnouncementsRouteImport } from './routes/admin/_gate/announcements'
import { Route as AdminGateBalancesRouteImport } from './routes/admin/_gate/balances'
import { Route as AdminGateCurrenciesRouteImport } from './routes/admin/_gate/currencies'
import { Route as AdminGateDashboardRouteImport } from './routes/admin/_gate/dashboard'
import { Route as AdminGateMessagesRouteImport } from './routes/admin/_gate/messages'
import { Route as AdminGateNewTransactionRouteImport } from './routes/admin/_gate/new-transaction'
import { Route as AdminGateReportsRouteImport } from './routes/admin/_gate/reports'
import { Route as AdminGateSettingsRouteImport } from './routes/admin/_gate/settings'
import { Route as AdminGateTransactionsRouteImport } from './routes/admin/_gate/transactions'
import { Route as AdminGateUsersRouteImport } from './routes/admin/_gate/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCardsRoute = AuthenticatedCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatementsRoute = AuthenticatedStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateRouteRoute = AdminGateRouteRouteImport.update({
  id: '/admin/_gate',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateActivityLogsRoute = AdminGateActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateAnnouncementsRoute = AdminGateAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateBalancesRoute = AdminGateBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateCurrenciesRoute = AdminGateCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateDashboardRoute = AdminGateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateMessagesRoute = AdminGateMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateNewTransactionRoute = AdminGateNewTransactionRouteImport.update({
  id: '/new-transaction',
  path: '/new-transaction',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateReportsRoute = AdminGateReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateSettingsRoute = AdminGateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateTransactionsRoute = AdminGateTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminGateRouteRoute,
} as any)
const AdminGateUsersRoute = AdminGateUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminGateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminGateRouteRouteWithChildren
  '/cards': typeof AuthenticatedCardsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/activity-logs': typeof AdminGateActivityLogsRoute
  '/admin/announcements': typeof AdminGateAnnouncementsRoute
  '/admin/balances': typeof AdminGateBalancesRoute
  '/admin/currencies': typeof AdminGateCurrenciesRoute
  '/admin/dashboard': typeof AdminGateDashboardRoute
  '/admin/messages': typeof AdminGateMessagesRoute
  '/admin/new-transaction': typeof AdminGateNewTransactionRoute
  '/admin/reports': typeof AdminGateReportsRoute
  '/admin/settings': typeof AdminGateSettingsRoute
  '/admin/transactions': typeof AdminGateTransactionsRoute
  '/admin/users': typeof AdminGateUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminIndexRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/activity-logs': typeof AdminGateActivityLogsRoute
  '/admin/announcements': typeof AdminGateAnnouncementsRoute
  '/admin/balances': typeof AdminGateBalancesRoute
  '/admin/currencies': typeof AdminGateCurrenciesRoute
  '/admin/dashboard': typeof AdminGateDashboardRoute
  '/admin/messages': typeof AdminGateMessagesRoute
  '/admin/new-transaction': typeof AdminGateNewTransactionRoute
  '/admin/reports': typeof AdminGateReportsRoute
  '/admin/settings': typeof AdminGateSettingsRoute
  '/admin/transactions': typeof AdminGateTransactionsRoute
  '/admin/users': typeof AdminGateUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/_gate': typeof AdminGateRouteRouteWithChildren
  '/_authenticated/cards': typeof AuthenticatedCardsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/statements': typeof AuthenticatedStatementsRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_gate/activity-logs': typeof AdminGateActivityLogsRoute
  '/admin/_gate/announcements': typeof AdminGateAnnouncementsRoute
  '/admin/_gate/balances': typeof AdminGateBalancesRoute
  '/admin/_gate/currencies': typeof AdminGateCurrenciesRoute
  '/admin/_gate/dashboard': typeof AdminGateDashboardRoute
  '/admin/_gate/messages': typeof AdminGateMessagesRoute
  '/admin/_gate/new-transaction': typeof AdminGateNewTransactionRoute
  '/admin/_gate/reports': typeof AdminGateReportsRoute
  '/admin/_gate/settings': typeof AdminGateSettingsRoute
  '/admin/_gate/transactions': typeof AdminGateTransactionsRoute
  '/admin/_gate/users': typeof AdminGateUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/cards'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/statements'
    | '/transfers'
    | '/admin/login'
    | '/admin/'
    | '/admin/activity-logs'
    | '/admin/announcements'
    | '/admin/balances'
    | '/admin/currencies'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/new-transaction'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/cards'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/statements'
    | '/transfers'
    | '/admin/login'
    | '/admin/activity-logs'
    | '/admin/announcements'
    | '/admin/balances'
    | '/admin/currencies'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/new-transaction'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/_gate'
    | '/_authenticated/cards'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/statements'
    | '/_authenticated/transfers'
    | '/admin/login'
    | '/admin/'
    | '/admin/_gate/activity-logs'
    | '/admin/_gate/announcements'
    | '/admin/_gate/balances'
    | '/admin/_gate/currencies'
    | '/admin/_gate/dashboard'
    | '/admin/_gate/messages'
    | '/admin/_gate/new-transaction'
    | '/admin/_gate/reports'
    | '/admin/_gate/settings'
    | '/admin/_gate/transactions'
    | '/admin/_gate/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminGateRouteRoute: typeof AdminGateRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cards': {
      id: '/_authenticated/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AuthenticatedCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statements': {
      id: '/_authenticated/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AuthenticatedStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate': {
      id: '/admin/_gate'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminGateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate/activity-logs': {
      id: '/admin/_gate/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminGateActivityLogsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/announcements': {
      id: '/admin/_gate/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminGateAnnouncementsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/balances': {
      id: '/admin/_gate/balances'
      path: '/balances'
      fullPath: '/admin/balances'
      preLoaderRoute: typeof AdminGateBalancesRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/currencies': {
      id: '/admin/_gate/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminGateCurrenciesRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/dashboard': {
      id: '/admin/_gate/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminGateDashboardRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/messages': {
      id: '/admin/_gate/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminGateMessagesRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/new-transaction': {
      id: '/admin/_gate/new-transaction'
      path: '/new-transaction'
      fullPath: '/admin/new-transaction'
      preLoaderRoute: typeof AdminGateNewTransactionRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/reports': {
      id: '/admin/_gate/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminGateReportsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/settings': {
      id: '/admin/_gate/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminGateSettingsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/transactions': {
      id: '/admin/_gate/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminGateTransactionsRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
    '/admin/_gate/users': {
      id: '/admin/_gate/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminGateUsersRouteImport
      parentRoute: typeof AdminGateRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCardsRoute: typeof AuthenticatedCardsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStatementsRoute: typeof AuthenticatedStatementsRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCardsRoute: AuthenticatedCardsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStatementsRoute: AuthenticatedStatementsRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminGateRouteRouteChildren {
  AdminGateActivityLogsRoute: typeof AdminGateActivityLogsRoute
  AdminGateAnnouncementsRoute: typeof AdminGateAnnouncementsRoute
  AdminGateBalancesRoute: typeof AdminGateBalancesRoute
  AdminGateCurrenciesRoute: typeof AdminGateCurrenciesRoute
  AdminGateDashboardRoute: typeof AdminGateDashboardRoute
  AdminGateMessagesRoute: typeof AdminGateMessagesRoute
  AdminGateNewTransactionRoute: typeof AdminGateNewTransactionRoute
  AdminGateReportsRoute: typeof AdminGateReportsRoute
  AdminGateSettingsRoute: typeof AdminGateSettingsRoute
  AdminGateTransactionsRoute: typeof AdminGateTransactionsRoute
  AdminGateUsersRoute: typeof AdminGateUsersRoute
}

const AdminGateRouteRouteChildren: AdminGateRouteRouteChildren = {
  AdminGateActivityLogsRoute: AdminGateActivityLogsRoute,
  AdminGateAnnouncementsRoute: AdminGateAnnouncementsRoute,
  AdminGateBalancesRoute: AdminGateBalancesRoute,
  AdminGateCurrenciesRoute: AdminGateCurrenciesRoute,
  AdminGateDashboardRoute: AdminGateDashboardRoute,
  AdminGateMessagesRoute: AdminGateMessagesRoute,
  AdminGateNewTransactionRoute: AdminGateNewTransactionRoute,
  AdminGateReportsRoute: AdminGateReportsRoute,
  AdminGateSettingsRoute: AdminGateSettingsRoute,
  AdminGateTransactionsRoute: AdminGateTransactionsRoute,
  AdminGateUsersRoute: AdminGateUsersRoute,
}

const AdminGateRouteRouteWithChildren = AdminGateRouteRoute._addFileChildren(
  AdminGateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminGateRouteRoute: AdminGateRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
